In [2]:
import numpy as np
print(np.__version__)

2.4.1


In [ ]:
#1. creating array

In [3]:
list1=[1,2,3]
print(list1)

[1, 2, 3]


In [4]:
arr_list1=np.array(list1)
print(arr_list1)

[1 2 3]


In [11]:
print(type(arr_list1))
print(arr_list1.ndim)

<class 'numpy.ndarray'>
1


In [8]:
list1=[1,2,3]
list2=[4,5,6]
arr_list_1_2=np.array([list1,list2])
print(arr_list_1_2)
print("dimentional",arr_list_1_2.ndim)

[[1 2 3]
 [4 5 6]]
dimentional 2


In [9]:
list1=[1,2,3]
list2=[4,5,6]
list3=[7,8,9]
arr_list_1_2_3=np.array([list1,list2,list3])
print(arr_list_1_2_3)
print("dimentional",arr_list_1_2_3.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
dimentional 2


In [12]:
# 2. numpy array attributes
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [15]:
print("shape:",arr1.shape)#says number of rows and column
print("size:",arr1.size)#says how much elements in the array
print("dtype:",arr1.dtype) #says the datatype of the elements inside the array
print("ndim:",arr1.ndim)#says the dimension of the array

shape: (2, 3)
size: 6
dtype: int64
ndim: 2


In [22]:
# 2.0 homework problem (create 2 array -1d and 3d , and find its attribute
#1 dimensional array
list1=[1,2,3,4,5,6]
arr_list1=np.array(list1)
print(arr_list1)
print("shape :",arr_list1.shape)
print("size :",arr_list1.size)
print("dtype :",arr_list1.dtype)
print("dimensional :",arr_list1.ndim)

[1 2 3 4 5 6]
shape : (6,)
size : 6
dtype : int64
dimensional : 1


In [31]:
list1=[1, 2, 3, 4, 5]
list2=[10, 20, 30, 40, 50]
list3=[100, 200, 300, 400, 500]
arr_list123 = np.array([[list1,list2,list3]])
print(arr_list123)
print("SHAPE:",arr_list123.shape)
print("Size:",arr_list123.size)
print("dtype:",arr_list123.dtype)
print("dimensional :",arr_list123.ndim)

[[[  1   2   3   4   5]
  [ 10  20  30  40  50]
  [100 200 300 400 500]]]
SHAPE: (1, 3, 5)
Size: 15
dtype: int64
dimensional : 3


In [ ]:
# 3.Array initialization methods

In [33]:
#zeros array
zero_arr=np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [39]:
#one array
one_array=np.ones((3,3))
print(one_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [43]:
#full array
full_arr=np.full((2,3),7)
print(full_arr)

[[7 7 7]
 [7 7 7]]


In [51]:
#identity matrix (always 3x3) square matrix
id_arr=np.eye(4)
print(id_arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
#empty array
import numpy as np
print(np.empty(2))

[0.00000000e+000 5.79374739e-312]


In [13]:
#evenly spaced array
import numpy as np
print(np.arange(2,10,2))

[2 4 6 8]


In [23]:
#specific number of equally (spaced) value between a range
print(np.linspace(1,10,5))

[ 1.    3.25  5.5   7.75 10.  ]


In [32]:
#random values array ( this is used for generating random integer)
r_arr=np.random.randint(1,10,size=(2,3))
print(r_arr)

[[9 8 5]
 [7 3 6]]


In [36]:
#random values array (this is used for generating random float values)
rf_arr=np.random.rand(2,2)
print(rf_arr)

[[0.36253812 0.73377376]
 [0.56684754 0.80727873]]


In [37]:
#indexing and slicing in the array
a=np.array([1,2,3,4,5,6,7,8])
print(a)

[1 2 3 4 5 6 7 8]


In [ ]:
#printing the value using the index number
print(a[3]) #4(at index 3 , 4 is there)
print(a[-1]) #8(at index -1 the last value is 8)

4
8


In [ ]:
#slicing
#syntax (start:stop:step)
print(a)
print("after performing slicing :")
print(a[0:5:2])
print(a[-1:5:-1])

[1 2 3 4 5 6 7 8]
after performing slicing :
[1 3 5]
[8 7]


In [61]:
#2dimension array slicing
arr_1=np.array([[1,2,3],[4,5,6]])
print(arr_1)
print("------------------------------")
print(arr_1[0])
print("------------------------------")
print(arr_1[1][2]) #it prints the first rows 3rd element

[[1 2 3]
 [4 5 6]]
------------------------------
[1 2 3]
------------------------------
6


In [65]:
#2dimension array slicing
arr_2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2)
print("------------------------------")
print(arr_2[0])
print("------------------------------")
print(arr_2[1])
print("------------------------------")
print(arr_2[2])
print("------------------------------")
print(arr_2[0][1])
print("------------------------------")
print(arr_2[1][2])
print("------------------------------")
print(arr_2[2][2])
print("------------------------------")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------
[1 2 3]
------------------------------
[4 5 6]
------------------------------
[7 8 9]
------------------------------
2
------------------------------
6
------------------------------
9
------------------------------


In [81]:
print(arr_2)
print("------------------------------")
print(arr_2[0:2,0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------
[[1 2]
 [4 5]]


In [6]:
#reshape
import numpy as np
a=np.array([1,2,3,4,5,6])
print(a)
print("--------------------------")
reshape1=a.reshape((2,3))
print(reshape1)
print("--------------------------")
reshape2=a.reshape((6,1))
print(reshape2)
print("--------------------------")

[1 2 3 4 5 6]
--------------------------
[[1 2 3]
 [4 5 6]]
--------------------------
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
--------------------------


In [7]:
#flattening - Creates a new copy of the array data
print(reshape1.flatten())

[1 2 3 4 5 6]


In [11]:
#ravel
a = np.array([[1, 2], [3, 4]])
b = a.ravel() #- may affect the original array
b[0] = 99
print(a)

[[99  2]
 [ 3  4]]


In [12]:
#flatten
a = np.array([[1, 2], [3, 4]])
b = a.flatten()
b[0] = 99
print(a)  # Original array unchanged

[[1 2]
 [3 4]]


In [3]:
#stacking and splitting
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [4]:
#splitting
c=np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [11]:
np.hsplit(c,3) # #horizontal split

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [13]:
np.vsplit(c,2) #vertical split

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [ ]:
#mathematical operations on array

In [15]:
a=np.array([1,2,3,-3])
print(a)

[ 1  2  3 -3]


In [16]:
print(a+10)
print(a-3)
print(a*2)
print(a/10)

[11 12 13  7]
[-2 -1  0 -6]
[ 2  4  6 -6]
[ 0.1  0.2  0.3 -0.3]


In [20]:
b=np.array([10,2,3,4,5])
print(b)
print(np.square(b))
print(np.sqrt(b))

[10  2  3  4  5]
[100   4   9  16  25]
[3.16227766 1.41421356 1.73205081 2.         2.23606798]


In [22]:
trigonometry=np.array([30,45,60,90])
print(np.sin(trigonometry))
print(np.cos(trigonometry))
print(np.tan(trigonometry))

[-0.98803162  0.85090352 -0.30481062  0.89399666]
[ 0.15425145  0.52532199 -0.95241298 -0.44807362]
[-6.4053312   1.61977519  0.32004039 -1.99520041]


In [33]:
#mulitidimensional array
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a*b)
print("==============")
print(a+b)
print("===============")
print(np.add(a,b))
print("===============")
print(np.subtract(b,a))
print("===============")
print(np.multiply(a,b))
print("===============")
print(np.divide(b,a))
print("===============")
print(np.dot(a,b)) #1x4=4 ,2x5=10 , 3x6=18 --> 4+10+18=32

[ 4 10 18]
[5 7 9]
[5 7 9]
[3 3 3]
[ 4 10 18]
[4.  2.5 2. ]
32


In [39]:
#transpose
print(a)
print("===============")
print(a.T)
print("===============")
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a1)
print("===============")
print(a1.T)

[1 2 3]
[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
#Statistical functions

In [40]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [42]:
print(np.sum(a))
print("===============")
print(np.mean(a))
print("===============")
print(np.std(a))
print("===============")
print(np.median(a))
print("===============")
print(np.min(a))
print("===============")
print(np.max(a))


21
3.5
1.707825127659933
3.5
1
6


In [ ]:
#array comparison

In [52]:
a=np.array([1,2,3])
b=np.array([4,5,3])
print(a)
print(b)
print(a==b) #comparing each element
print("===============")
print(np.array_equal(a,b)) #comparing complete array

[1 2 3]
[4 5 3]
[False False  True]
False


In [54]:
#Broadcasting
a=np.array([1,2,3])
b=np.array([4])
print(a+b)


[5 6 7]


In [59]:
a1=np.array([[1,2,3],[4,5,6]])
b2=np.array([4,5,3])
print(a1+b2)

[[ 5  7  6]
 [ 8 10  9]]


In [63]:
#handling with nun value(nan) and infinite value(inf)
arr=np.array([1,2,np.nan,np.inf])
print(arr)
print(np.isnan(arr)) #use this function to  check whether the null value exists or not
print(np.nan_to_num(arr)) # use this function for assigning a value  to the null value

[ 1.  2. nan inf]
[False False  True False]
[1.00000000e+000 2.00000000e+000 0.00000000e+000 1.79769313e+308]


In [64]:
#save and load arrays
arr=np.array([1,2,3])
print(arr)
np.save('my_array',arr)

[1 2 3]


In [77]:
a=np.random.randint(1,26,size=(5,5))
print(a)
print("===================================")
print(a[4:,0])
print(a[0:3,0:3])

[[13 21 11  5  7]
 [ 5 18  9 20 13]
 [12 22  2  1 22]
 [ 3  4 15  4  5]
 [11  6  6 21 23]]
[11]
[[13 21 11]
 [ 5 18  9]
 [12 22  2]]
