In [2]:
import numpy as np
print(np.__version__)


2.4.1


In [ ]:
#1. creating array

In [3]:
list1=[1,2,3]
print(list1)

[1, 2, 3]


In [4]:
arr_list1=np.array(list1)
print(arr_list1)

[1 2 3]


In [11]:
print(type(arr_list1))
print(arr_list1.ndim)

<class 'numpy.ndarray'>
1


In [8]:
list1=[1,2,3]
list2=[4,5,6]
arr_list_1_2=np.array([list1,list2])
print(arr_list_1_2)
print("dimentional",arr_list_1_2.ndim)

[[1 2 3]
 [4 5 6]]
dimentional 2


In [9]:
list1=[1,2,3]
list2=[4,5,6]
list3=[7,8,9]
arr_list_1_2_3=np.array([list1,list2,list3])
print(arr_list_1_2_3)
print("dimentional",arr_list_1_2_3.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
dimentional 2


In [12]:
# 2. numpy array attributes
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [15]:
print("shape:",arr1.shape)#says number of rows and column
print("size:",arr1.size)#says how much elements in the array
print("dtype:",arr1.dtype) #says the datatype of the elements inside the array
print("ndim:",arr1.ndim)#says the dimension of the array

shape: (2, 3)
size: 6
dtype: int64
ndim: 2


In [22]:
# 2.0 homework problem (create 2 array -1d and 3d , and find it's attribute
#1 dimensional array
list1=[1,2,3,4,5,6]
arr_list1=np.array(list1)
print(arr_list1)
print("shape :",arr_list1.shape)
print("size :",arr_list1.size)
print("dtype :",arr_list1.dtype)
print("dimensional :",arr_list1.ndim)

[1 2 3 4 5 6]
shape : (6,)
size : 6
dtype : int64
dimensional : 1


In [31]:
list1=[1, 2, 3, 4, 5]
list2=[10, 20, 30, 40, 50]
list3=[100, 200, 300, 400, 500]
arr_list123 = np.array([[list1,list2,list3]])
print(arr_list123)
print("SHAPE:",arr_list123.shape)
print("Size:",arr_list123.size)
print("dtype:",arr_list123.dtype)
print("dimensional :",arr_list123.ndim)

[[[  1   2   3   4   5]
  [ 10  20  30  40  50]
  [100 200 300 400 500]]]
SHAPE: (1, 3, 5)
Size: 15
dtype: int64
dimensional : 3


In [ ]:
# 3.Array initialization methods

In [33]:
#zeros array
zero_arr=np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [35]:
#one array
one_array=np.ones((2,3))
print(one_array)

[[1. 1. 1.]
 [1. 1. 1.]]
