In [2]:
import numpy as np
print(np.__version__)

2.4.1


In [ ]:
#1. creating array

In [3]:
list1=[1,2,3]
print(list1)

[1, 2, 3]


In [4]:
arr_list1=np.array(list1)
print(arr_list1)

[1 2 3]


In [11]:
print(type(arr_list1))
print(arr_list1.ndim)

<class 'numpy.ndarray'>
1


In [8]:
list1=[1,2,3]
list2=[4,5,6]
arr_list_1_2=np.array([list1,list2])
print(arr_list_1_2)
print("dimentional",arr_list_1_2.ndim)

[[1 2 3]
 [4 5 6]]
dimentional 2


In [9]:
list1=[1,2,3]
list2=[4,5,6]
list3=[7,8,9]
arr_list_1_2_3=np.array([list1,list2,list3])
print(arr_list_1_2_3)
print("dimentional",arr_list_1_2_3.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
dimentional 2


In [12]:
# 2. numpy array attributes
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [15]:
print("shape:",arr1.shape)#says number of rows and column
print("size:",arr1.size)#says how much elements in the array
print("dtype:",arr1.dtype) #says the datatype of the elements inside the array
print("ndim:",arr1.ndim)#says the dimension of the array

shape: (2, 3)
size: 6
dtype: int64
ndim: 2


In [22]:
# 2.0 homework problem (create 2 array -1d and 3d , and find it's attribute
#1 dimensional array
list1=[1,2,3,4,5,6]
arr_list1=np.array(list1)
print(arr_list1)
print("shape :",arr_list1.shape)
print("size :",arr_list1.size)
print("dtype :",arr_list1.dtype)
print("dimensional :",arr_list1.ndim)

[1 2 3 4 5 6]
shape : (6,)
size : 6
dtype : int64
dimensional : 1


In [31]:
list1=[1, 2, 3, 4, 5]
list2=[10, 20, 30, 40, 50]
list3=[100, 200, 300, 400, 500]
arr_list123 = np.array([[list1,list2,list3]])
print(arr_list123)
print("SHAPE:",arr_list123.shape)
print("Size:",arr_list123.size)
print("dtype:",arr_list123.dtype)
print("dimensional :",arr_list123.ndim)

[[[  1   2   3   4   5]
  [ 10  20  30  40  50]
  [100 200 300 400 500]]]
SHAPE: (1, 3, 5)
Size: 15
dtype: int64
dimensional : 3


In [ ]:
# 3.Array initialization methods

In [33]:
#zeros array
zero_arr=np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [39]:
#one array
one_array=np.ones((3,3))
print(one_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [43]:
#full array
full_arr=np.full((2,3),7)
print(full_arr)

[[7 7 7]
 [7 7 7]]


In [51]:
#identity matrix (always 3x3) square matrix
id_arr=np.eye(4)
print(id_arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
#empty array
import numpy as np
print(np.empty(2))

[0.00000000e+000 5.79374739e-312]


In [13]:
#evenly spaced array
import numpy as np
print(np.arange(2,10,2))

[2 4 6 8]


In [23]:
#specific number of equally (spaced) value between a range
print(np.linspace(1,10,5))

[ 1.    3.25  5.5   7.75 10.  ]


In [32]:
#random values array ( this is used for generating random integer)
r_arr=np.random.randint(1,10,size=(2,3))
print(r_arr)

[[9 8 5]
 [7 3 6]]


In [36]:
#random values array (this is used for generating random float values)
rf_arr=np.random.rand(2,2)
print(rf_arr)

[[0.36253812 0.73377376]
 [0.56684754 0.80727873]]


In [37]:
#indexing and slicing in the array
a=np.array([1,2,3,4,5,6,7,8])
print(a)

[1 2 3 4 5 6 7 8]


In [ ]:
#printing the value using the index number
print(a[3]) #4(at index 3 , 4 is there)
print(a[-1]) #8(at index -1 the last value is 8)

4
8


In [ ]:
#slicing
 #syntax (start:stop:step)
 print(a)
 print("after performing slicing :")
 print(a[0:5:2])
 print(a[-1:5:-1])

[1 2 3 4 5 6 7 8]
after performing slicing :
[1 3 5]
[8 7]


In [61]:
#2dimension array slicing
arr_1=np.array([[1,2,3],[4,5,6]])
print(arr_1)
print("------------------------------")
print(arr_1[0])
print("------------------------------")
print(arr_1[1][2]) #it prints the first rows 3rd element

[[1 2 3]
 [4 5 6]]
------------------------------
[1 2 3]
------------------------------
6


In [65]:
#2dimension array slicing
arr_2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2)
print("------------------------------")
print(arr_2[0])
print("------------------------------")
print(arr_2[1])
print("------------------------------")
print(arr_2[2])
print("------------------------------")
print(arr_2[0][1])
print("------------------------------")
print(arr_2[1][2])
print("------------------------------")
print(arr_2[2][2])
print("------------------------------")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------
[1 2 3]
------------------------------
[4 5 6]
------------------------------
[7 8 9]
------------------------------
2
------------------------------
6
------------------------------
9
------------------------------


In [81]:
print(arr_2)
print("------------------------------")
print(arr_2[0:2,0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------
[[1 2]
 [4 5]]
